title: Security+ SY0-601 Notes and Resources
description: This repo was created to assist collecting notes and resources to assist myself and others with studying for and passing the Security+ SY0-601 exam which is administered by CompTIA.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
